# Generated by Django 5.2.3 on 2025-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewerly_app', '0003_pricelist_pricelistentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
