# Generated by Django 5.2.3 on 2025-07-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewerly_app', '0004_alter_pricelist_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.RenameModel(
            old_name='PriceListEntries',
            new_name='PriceListEntry',
        ),
        migrations.CreateModel(
            name='ClientMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.client')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.material')),
            ],
            options={
                'db_table': 'client_materials',
            },
        ),
    ]
