# Generated by Django 5.2.3 on 2025-07-11 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewerly_app', '0006_materialauditentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialauditentry',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.client'),
        ),
        migrations.AlterModelTable(
            name='materialauditentry',
            table='material_audit_entries',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now=True, null=True)),
                ('cancellation', models.TextField(null=True)),
                ('discount', models.SmallIntegerField(null=True)),
                ('loss', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_with_discount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.client')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.material')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.product')),
            ],
            options={
                'db_table': 'order_products',
            },
        ),
    ]
