# Generated by Django 5.2.3 on 2025-07-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewerly_app', '0007_alter_materialauditentry_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.order')),
            ],
            options={
                'db_table': 'employee_orders',
            },
        ),
    ]
