# Generated by Django 5.2.3 on 2025-07-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewerly_app', '0008_employee_employeeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(auto_now=True, null=True)),
                ('issued', models.DecimalField(decimal_places=5, max_digits=17)),
                ('returned', models.DecimalField(decimal_places=5, max_digits=17, null=True)),
                ('loss', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('returned_with_loss', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.order')),
            ],
            options={
                'db_table': 'work_units',
            },
        ),
    ]
