# Generated by Django 5.2.3 on 2025-07-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewerly_app', '0009_workunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.client')),
            ],
            options={
                'db_table': 'material_audit_records',
            },
        ),
        migrations.CreateModel(
            name='MaterialAuditRecordRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.material')),
                ('material_audit_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewerly_app.materialauditrecord')),
            ],
            options={
                'db_table': 'material_audit_record_rows',
            },
        ),
        migrations.DeleteModel(
            name='MaterialAuditEntry',
        ),
    ]
