services:
  postgres:
    container_name: postgres
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: